In [1]:
#Used libraries

import os
import pandas as pd
import pydicom
import matplotlib.pylab as plt
import numpy as np

print("Imported!")

Imported!


In [2]:
# Specify the root directory where the DICOM images are stored

root_dir = 'C:/Users/esteb/OneDrive - Universidad Politecnica Salesiana/Papers/Cancer cerebral/Dataset/manifest-1678464337678/Brain-TR-GammaKnife/'

In [3]:
df = pd.DataFrame(columns=['File', 'PatientID', 'StudyDate', 'SeriesDescription','StudyDescription'])


In [7]:
file_path = "C:/Users/esteb/OneDrive - Universidad Politecnica Salesiana/Papers/Cancer cerebral/Dataset/manifest-1678464337678/Brain-TR-GammaKnife/GK_103/12-18-2014-NA-MR BRAIN W WO IV CONTRAST-94259/13.000000-t1mprtraiso-42794/1-001.dcm"
dcm = pydicom.dcmread(file_path)
array=dcm.pixel_array 
print(array)
print(array.shape)
dcm

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
(256, 256)


Dataset.file_meta -------------------------------
(0002, 0000) File Meta Information Group Length  UL: 204
(0002, 0001) File Meta Information Version       OB: b'\x00\x01'
(0002, 0002) Media Storage SOP Class UID         UI: MR Image Storage
(0002, 0003) Media Storage SOP Instance UID      UI: 1.3.6.1.4.1.14519.5.2.1.290511021106575077095027273690077523161
(0002, 0010) Transfer Syntax UID                 UI: Implicit VR Little Endian
(0002, 0012) Implementation Class UID            UI: 1.3.6.1.4.1.22213.1.143
(0002, 0013) Implementation Version Name         SH: '0.5'
(0002, 0016) Source Application Entity Title     AE: 'POSDA'
-------------------------------------------------
(0008, 0005) Specific Character Set              CS: 'ISO_IR 100'
(0008, 0008) Image Type                          CS: ['ORIGINAL', 'PRIMARY', 'M', 'NORM', 'DIS3D', 'DIS2D']
(0008, 0012) Instance Creation Date              DA: '20141218'
(0008, 0013) Instance Creation Time              TM: '132131.001000'
(0008, 0

In [61]:
count = 0
for subdir, dirs, files in os.walk(root_dir):
    if count<10:
        count += 1
        for file in files:
            # Check if the file is a DICOM image
            if file.endswith('.dcm'):
                # Create the full file path
                file_path = os.path.join(subdir, file)
                file_path=file_path.replace('\\','/')
                dcm = pydicom.dcmread(file_path)
                print(file)
                print(file_path)
                try:
                    array=dcm.pixel_array
                    print(array)
                    print
                    print(len(array))
                except:
                    print("No image data")
                print()

1-1.dcm
C:/Users/esteb/OneDrive - Universidad Politecnica Salesiana/Papers/Cancer cerebral/Dataset/manifest-1678464337678/Brain-TR-GammaKnife/GK_103/04-18-2014-NA-MR GAMMA KNIFE PLANNING BRAIN W IV CONTRAST-49648/1.000000-Course 1-21101/1-1.dcm
No image data

1-1.dcm
C:/Users/esteb/OneDrive - Universidad Politecnica Salesiana/Papers/Cancer cerebral/Dataset/manifest-1678464337678/Brain-TR-GammaKnife/GK_103/04-18-2014-NA-MR GAMMA KNIFE PLANNING BRAIN W IV CONTRAST-49648/28641.000000-Comp Dose-71122/1-1.dcm
[[[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 ...

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0

1-035.dcm
C:/Users/esteb/OneDrive - Universidad Politecnica Salesiana/Papers/Cancer cerebral/Dataset/manifest-1678464337678/Brain-TR-GammaKnife/GK_103/04-18-2014-NA-MR GAMMA KNIFE PLANNING BRAIN W IV CONTRAST-49648/4.000000-t1mprtraiso-40897/1-035.dcm
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
256

1-036.dcm
C:/Users/esteb/OneDrive - Universidad Politecnica Salesiana/Papers/Cancer cerebral/Dataset/manifest-1678464337678/Brain-TR-GammaKnife/GK_103/04-18-2014-NA-MR GAMMA KNIFE PLANNING BRAIN W IV CONTRAST-49648/4.000000-t1mprtraiso-40897/1-036.dcm
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
256

1-037.dcm
C:/Users/esteb/OneDrive - Universidad Politecnica Salesiana/Papers/Cancer cerebral/Dataset/manifest-1678464337678/Brain-TR-GammaKnife/GK_103/04-18-2014-NA-MR GAMMA KNIFE PLANNING BRAIN W IV CONTRAST-49648/4.000000-t1mprtraiso-40897/1-03

1-073.dcm
C:/Users/esteb/OneDrive - Universidad Politecnica Salesiana/Papers/Cancer cerebral/Dataset/manifest-1678464337678/Brain-TR-GammaKnife/GK_103/04-18-2014-NA-MR GAMMA KNIFE PLANNING BRAIN W IV CONTRAST-49648/4.000000-t1mprtraiso-40897/1-073.dcm
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
256

1-074.dcm
C:/Users/esteb/OneDrive - Universidad Politecnica Salesiana/Papers/Cancer cerebral/Dataset/manifest-1678464337678/Brain-TR-GammaKnife/GK_103/04-18-2014-NA-MR GAMMA KNIFE PLANNING BRAIN W IV CONTRAST-49648/4.000000-t1mprtraiso-40897/1-074.dcm
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
256

1-075.dcm
C:/Users/esteb/OneDrive - Universidad Politecnica Salesiana/Papers/Cancer cerebral/Dataset/manifest-1678464337678/Brain-TR-GammaKnife/GK_103/04-18-2014-NA-MR GAMMA KNIFE PLANNING BRAIN W IV CONTRAST-49648/4.000000-t1mprtraiso-40897/1-07

1-125.dcm
C:/Users/esteb/OneDrive - Universidad Politecnica Salesiana/Papers/Cancer cerebral/Dataset/manifest-1678464337678/Brain-TR-GammaKnife/GK_103/04-18-2014-NA-MR GAMMA KNIFE PLANNING BRAIN W IV CONTRAST-49648/4.000000-t1mprtraiso-40897/1-125.dcm
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
256

1-126.dcm
C:/Users/esteb/OneDrive - Universidad Politecnica Salesiana/Papers/Cancer cerebral/Dataset/manifest-1678464337678/Brain-TR-GammaKnife/GK_103/04-18-2014-NA-MR GAMMA KNIFE PLANNING BRAIN W IV CONTRAST-49648/4.000000-t1mprtraiso-40897/1-126.dcm
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
256

1-127.dcm
C:/Users/esteb/OneDrive - Universidad Politecnica Salesiana/Papers/Cancer cerebral/Dataset/manifest-1678464337678/Brain-TR-GammaKnife/GK_103/04-18-2014-NA-MR GAMMA KNIFE PLANNING BRAIN W IV CONTRAST-49648/4.000000-t1mprtraiso-40897/1-12

1-153.dcm
C:/Users/esteb/OneDrive - Universidad Politecnica Salesiana/Papers/Cancer cerebral/Dataset/manifest-1678464337678/Brain-TR-GammaKnife/GK_103/04-18-2014-NA-MR GAMMA KNIFE PLANNING BRAIN W IV CONTRAST-49648/4.000000-t1mprtraiso-40897/1-153.dcm
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
256

1-154.dcm
C:/Users/esteb/OneDrive - Universidad Politecnica Salesiana/Papers/Cancer cerebral/Dataset/manifest-1678464337678/Brain-TR-GammaKnife/GK_103/04-18-2014-NA-MR GAMMA KNIFE PLANNING BRAIN W IV CONTRAST-49648/4.000000-t1mprtraiso-40897/1-154.dcm
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
256

1-155.dcm
C:/Users/esteb/OneDrive - Universidad Politecnica Salesiana/Papers/Cancer cerebral/Dataset/manifest-1678464337678/Brain-TR-GammaKnife/GK_103/04-18-2014-NA-MR GAMMA KNIFE PLANNING BRAIN W IV CONTRAST-49648/4.000000-t1mprtraiso-40897/1-15

1-194.dcm
C:/Users/esteb/OneDrive - Universidad Politecnica Salesiana/Papers/Cancer cerebral/Dataset/manifest-1678464337678/Brain-TR-GammaKnife/GK_103/04-18-2014-NA-MR GAMMA KNIFE PLANNING BRAIN W IV CONTRAST-49648/4.000000-t1mprtraiso-40897/1-194.dcm
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
256

1-195.dcm
C:/Users/esteb/OneDrive - Universidad Politecnica Salesiana/Papers/Cancer cerebral/Dataset/manifest-1678464337678/Brain-TR-GammaKnife/GK_103/04-18-2014-NA-MR GAMMA KNIFE PLANNING BRAIN W IV CONTRAST-49648/4.000000-t1mprtraiso-40897/1-195.dcm
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
256

1-196.dcm
C:/Users/esteb/OneDrive - Universidad Politecnica Salesiana/Papers/Cancer cerebral/Dataset/manifest-1678464337678/Brain-TR-GammaKnife/GK_103/04-18-2014-NA-MR GAMMA KNIFE PLANNING BRAIN W IV CONTRAST-49648/4.000000-t1mprtraiso-40897/1-19

1-010.dcm
C:/Users/esteb/OneDrive - Universidad Politecnica Salesiana/Papers/Cancer cerebral/Dataset/manifest-1678464337678/Brain-TR-GammaKnife/GK_103/12-18-2014-NA-MR BRAIN W WO IV CONTRAST-94259/13.000000-t1mprtraiso-42794/1-010.dcm
[[ 0  0  0 ...  0  0  0]
 [ 0  0  9 ...  0  0  0]
 [ 0 11  4 ...  0  0  0]
 ...
 [ 0  0  0 ...  0  0  0]
 [ 0  0  0 ...  0  0  0]
 [ 0  0  0 ...  0  0  0]]
256

1-011.dcm
C:/Users/esteb/OneDrive - Universidad Politecnica Salesiana/Papers/Cancer cerebral/Dataset/manifest-1678464337678/Brain-TR-GammaKnife/GK_103/12-18-2014-NA-MR BRAIN W WO IV CONTRAST-94259/13.000000-t1mprtraiso-42794/1-011.dcm
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 9 5 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
256

1-012.dcm
C:/Users/esteb/OneDrive - Universidad Politecnica Salesiana/Papers/Cancer cerebral/Dataset/manifest-1678464337678/Brain-TR-GammaKnife/GK_103/12-18-2014-NA-MR BRAIN W WO IV CONTRAST-94259/13.000000-t1mprtraiso-42794/1-012.dcm
[[0 0 0 .

1-043.dcm
C:/Users/esteb/OneDrive - Universidad Politecnica Salesiana/Papers/Cancer cerebral/Dataset/manifest-1678464337678/Brain-TR-GammaKnife/GK_103/12-18-2014-NA-MR BRAIN W WO IV CONTRAST-94259/13.000000-t1mprtraiso-42794/1-043.dcm
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
256

1-044.dcm
C:/Users/esteb/OneDrive - Universidad Politecnica Salesiana/Papers/Cancer cerebral/Dataset/manifest-1678464337678/Brain-TR-GammaKnife/GK_103/12-18-2014-NA-MR BRAIN W WO IV CONTRAST-94259/13.000000-t1mprtraiso-42794/1-044.dcm
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
256

1-045.dcm
C:/Users/esteb/OneDrive - Universidad Politecnica Salesiana/Papers/Cancer cerebral/Dataset/manifest-1678464337678/Brain-TR-GammaKnife/GK_103/12-18-2014-NA-MR BRAIN W WO IV CONTRAST-94259/13.000000-t1mprtraiso-42794/1-045.dcm
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0

1-066.dcm
C:/Users/esteb/OneDrive - Universidad Politecnica Salesiana/Papers/Cancer cerebral/Dataset/manifest-1678464337678/Brain-TR-GammaKnife/GK_103/12-18-2014-NA-MR BRAIN W WO IV CONTRAST-94259/13.000000-t1mprtraiso-42794/1-066.dcm
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
256

1-067.dcm
C:/Users/esteb/OneDrive - Universidad Politecnica Salesiana/Papers/Cancer cerebral/Dataset/manifest-1678464337678/Brain-TR-GammaKnife/GK_103/12-18-2014-NA-MR BRAIN W WO IV CONTRAST-94259/13.000000-t1mprtraiso-42794/1-067.dcm
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
256

1-068.dcm
C:/Users/esteb/OneDrive - Universidad Politecnica Salesiana/Papers/Cancer cerebral/Dataset/manifest-1678464337678/Brain-TR-GammaKnife/GK_103/12-18-2014-NA-MR BRAIN W WO IV CONTRAST-94259/13.000000-t1mprtraiso-42794/1-068.dcm
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0

1-093.dcm
C:/Users/esteb/OneDrive - Universidad Politecnica Salesiana/Papers/Cancer cerebral/Dataset/manifest-1678464337678/Brain-TR-GammaKnife/GK_103/12-18-2014-NA-MR BRAIN W WO IV CONTRAST-94259/13.000000-t1mprtraiso-42794/1-093.dcm
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
256

1-094.dcm
C:/Users/esteb/OneDrive - Universidad Politecnica Salesiana/Papers/Cancer cerebral/Dataset/manifest-1678464337678/Brain-TR-GammaKnife/GK_103/12-18-2014-NA-MR BRAIN W WO IV CONTRAST-94259/13.000000-t1mprtraiso-42794/1-094.dcm
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
256

1-095.dcm
C:/Users/esteb/OneDrive - Universidad Politecnica Salesiana/Papers/Cancer cerebral/Dataset/manifest-1678464337678/Brain-TR-GammaKnife/GK_103/12-18-2014-NA-MR BRAIN W WO IV CONTRAST-94259/13.000000-t1mprtraiso-42794/1-095.dcm
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0

1-119.dcm
C:/Users/esteb/OneDrive - Universidad Politecnica Salesiana/Papers/Cancer cerebral/Dataset/manifest-1678464337678/Brain-TR-GammaKnife/GK_103/12-18-2014-NA-MR BRAIN W WO IV CONTRAST-94259/13.000000-t1mprtraiso-42794/1-119.dcm
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
256

1-120.dcm
C:/Users/esteb/OneDrive - Universidad Politecnica Salesiana/Papers/Cancer cerebral/Dataset/manifest-1678464337678/Brain-TR-GammaKnife/GK_103/12-18-2014-NA-MR BRAIN W WO IV CONTRAST-94259/13.000000-t1mprtraiso-42794/1-120.dcm
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
256

1-121.dcm
C:/Users/esteb/OneDrive - Universidad Politecnica Salesiana/Papers/Cancer cerebral/Dataset/manifest-1678464337678/Brain-TR-GammaKnife/GK_103/12-18-2014-NA-MR BRAIN W WO IV CONTRAST-94259/13.000000-t1mprtraiso-42794/1-121.dcm
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0

1-142.dcm
C:/Users/esteb/OneDrive - Universidad Politecnica Salesiana/Papers/Cancer cerebral/Dataset/manifest-1678464337678/Brain-TR-GammaKnife/GK_103/12-18-2014-NA-MR BRAIN W WO IV CONTRAST-94259/13.000000-t1mprtraiso-42794/1-142.dcm
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
256

1-143.dcm
C:/Users/esteb/OneDrive - Universidad Politecnica Salesiana/Papers/Cancer cerebral/Dataset/manifest-1678464337678/Brain-TR-GammaKnife/GK_103/12-18-2014-NA-MR BRAIN W WO IV CONTRAST-94259/13.000000-t1mprtraiso-42794/1-143.dcm
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
256

1-144.dcm
C:/Users/esteb/OneDrive - Universidad Politecnica Salesiana/Papers/Cancer cerebral/Dataset/manifest-1678464337678/Brain-TR-GammaKnife/GK_103/12-18-2014-NA-MR BRAIN W WO IV CONTRAST-94259/13.000000-t1mprtraiso-42794/1-144.dcm
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0

1-169.dcm
C:/Users/esteb/OneDrive - Universidad Politecnica Salesiana/Papers/Cancer cerebral/Dataset/manifest-1678464337678/Brain-TR-GammaKnife/GK_103/12-18-2014-NA-MR BRAIN W WO IV CONTRAST-94259/13.000000-t1mprtraiso-42794/1-169.dcm
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
256

1-170.dcm
C:/Users/esteb/OneDrive - Universidad Politecnica Salesiana/Papers/Cancer cerebral/Dataset/manifest-1678464337678/Brain-TR-GammaKnife/GK_103/12-18-2014-NA-MR BRAIN W WO IV CONTRAST-94259/13.000000-t1mprtraiso-42794/1-170.dcm
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
256

1-171.dcm
C:/Users/esteb/OneDrive - Universidad Politecnica Salesiana/Papers/Cancer cerebral/Dataset/manifest-1678464337678/Brain-TR-GammaKnife/GK_103/12-18-2014-NA-MR BRAIN W WO IV CONTRAST-94259/13.000000-t1mprtraiso-42794/1-171.dcm
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0

1-207.dcm
C:/Users/esteb/OneDrive - Universidad Politecnica Salesiana/Papers/Cancer cerebral/Dataset/manifest-1678464337678/Brain-TR-GammaKnife/GK_103/12-18-2014-NA-MR BRAIN W WO IV CONTRAST-94259/13.000000-t1mprtraiso-42794/1-207.dcm
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
256

1-208.dcm
C:/Users/esteb/OneDrive - Universidad Politecnica Salesiana/Papers/Cancer cerebral/Dataset/manifest-1678464337678/Brain-TR-GammaKnife/GK_103/12-18-2014-NA-MR BRAIN W WO IV CONTRAST-94259/13.000000-t1mprtraiso-42794/1-208.dcm
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
256

1-209.dcm
C:/Users/esteb/OneDrive - Universidad Politecnica Salesiana/Papers/Cancer cerebral/Dataset/manifest-1678464337678/Brain-TR-GammaKnife/GK_103/12-18-2014-NA-MR BRAIN W WO IV CONTRAST-94259/13.000000-t1mprtraiso-42794/1-209.dcm
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0

1-234.dcm
C:/Users/esteb/OneDrive - Universidad Politecnica Salesiana/Papers/Cancer cerebral/Dataset/manifest-1678464337678/Brain-TR-GammaKnife/GK_103/12-18-2014-NA-MR BRAIN W WO IV CONTRAST-94259/13.000000-t1mprtraiso-42794/1-234.dcm
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
256

1-235.dcm
C:/Users/esteb/OneDrive - Universidad Politecnica Salesiana/Papers/Cancer cerebral/Dataset/manifest-1678464337678/Brain-TR-GammaKnife/GK_103/12-18-2014-NA-MR BRAIN W WO IV CONTRAST-94259/13.000000-t1mprtraiso-42794/1-235.dcm
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
256

1-236.dcm
C:/Users/esteb/OneDrive - Universidad Politecnica Salesiana/Papers/Cancer cerebral/Dataset/manifest-1678464337678/Brain-TR-GammaKnife/GK_103/12-18-2014-NA-MR BRAIN W WO IV CONTRAST-94259/13.000000-t1mprtraiso-42794/1-236.dcm
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0

In [80]:
for subdir, dirs, files in os.walk(root_dir):
    for file in files:
        # Check if the file is a DICOM image
        if file.endswith('.dcm'):
            # Create the full file path
            file_path = os.path.join(subdir, file)
            file_path=file_path.replace('\\','/')
            dcm = pydicom.dcmread(file_path)
            print(file)
            print(file_path)
            try:
                
                patient_id = dcm.PatientID
                print(patient_id)
                study_date = dcm.StudyDate
                print(study_date)
                
                array=dcm.pixel_array
                
                 # Append the metadata to the DataFrame
                df = df.append({'File': file_path, 'PatientID': patient_id, 'StudyDate': study_date,
                            'SeriesDescription': series_description,'StudyDescription': study_description}, ignore_index=True)

                
                #Transforming pixel matrix to columns
                
                pixel_matrix = np.reshape(array, (-1, array.shape[1]))
                column_names = ['Pixel{}'.format(i) for i in range(pixel_matrix.shape[1])]

                pixel_df = pd.DataFrame(pixel_matrix, columns=column_names)
                
                
                df = pd.concat([df, pixel_df], axis=1)
                
                print(f'Guardado paciente: {patient_id}')

            except:
              print("No image data")
            print()

1-1.dcm
C:/Users/esteb/OneDrive - Universidad Politecnica Salesiana/Papers/Cancer cerebral/Dataset/manifest-1678464337678/Brain-TR-GammaKnife/GK_103/04-18-2014-NA-MR GAMMA KNIFE PLANNING BRAIN W IV CONTRAST-49648/1.000000-Course 1-21101/1-1.dcm
GK_103
20140418
No image data

1-1.dcm
C:/Users/esteb/OneDrive - Universidad Politecnica Salesiana/Papers/Cancer cerebral/Dataset/manifest-1678464337678/Brain-TR-GammaKnife/GK_103/04-18-2014-NA-MR GAMMA KNIFE PLANNING BRAIN W IV CONTRAST-49648/28641.000000-Comp Dose-71122/1-1.dcm
GK_103
20140418
No image data

1-001.dcm
C:/Users/esteb/OneDrive - Universidad Politecnica Salesiana/Papers/Cancer cerebral/Dataset/manifest-1678464337678/Brain-TR-GammaKnife/GK_103/04-18-2014-NA-MR GAMMA KNIFE PLANNING BRAIN W IV CONTRAST-49648/4.000000-t1mprtraiso-40897/1-001.dcm
GK_103
20140418
No image data

1-002.dcm
C:/Users/esteb/OneDrive - Universidad Politecnica Salesiana/Papers/Cancer cerebral/Dataset/manifest-1678464337678/Brain-TR-GammaKnife/GK_103/04-18-201

C:\Users\esteb\AppData\Local\Temp\ipykernel_5656\3567807760.py:21: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append({'File': file_path, 'PatientID': patient_id, 'StudyDate': study_date,
C:\Users\esteb\AppData\Local\Temp\ipykernel_5656\3567807760.py:21: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append({'File': file_path, 'PatientID': patient_id, 'StudyDate': study_date,
C:\Users\esteb\AppData\Local\Temp\ipykernel_5656\3567807760.py:21: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append({'File': file_path, 'PatientID': patient_id, 'StudyDate': study_date,
C:\Users\esteb\AppData\Local\Temp\ipykernel_5656\3567807760.py:21: FutureWarning: The frame.append method is deprecated and will be removed

1-009.dcm
C:/Users/esteb/OneDrive - Universidad Politecnica Salesiana/Papers/Cancer cerebral/Dataset/manifest-1678464337678/Brain-TR-GammaKnife/GK_103/04-18-2014-NA-MR GAMMA KNIFE PLANNING BRAIN W IV CONTRAST-49648/4.000000-t1mprtraiso-40897/1-009.dcm
GK_103
20140418
No image data

1-010.dcm
C:/Users/esteb/OneDrive - Universidad Politecnica Salesiana/Papers/Cancer cerebral/Dataset/manifest-1678464337678/Brain-TR-GammaKnife/GK_103/04-18-2014-NA-MR GAMMA KNIFE PLANNING BRAIN W IV CONTRAST-49648/4.000000-t1mprtraiso-40897/1-010.dcm
GK_103
20140418
No image data

1-011.dcm
C:/Users/esteb/OneDrive - Universidad Politecnica Salesiana/Papers/Cancer cerebral/Dataset/manifest-1678464337678/Brain-TR-GammaKnife/GK_103/04-18-2014-NA-MR GAMMA KNIFE PLANNING BRAIN W IV CONTRAST-49648/4.000000-t1mprtraiso-40897/1-011.dcm
GK_103
20140418
No image data

1-012.dcm
C:/Users/esteb/OneDrive - Universidad Politecnica Salesiana/Papers/Cancer cerebral/Dataset/manifest-1678464337678/Brain-TR-GammaKnife/GK_103/

C:\Users\esteb\AppData\Local\Temp\ipykernel_5656\3567807760.py:21: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append({'File': file_path, 'PatientID': patient_id, 'StudyDate': study_date,
C:\Users\esteb\AppData\Local\Temp\ipykernel_5656\3567807760.py:21: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append({'File': file_path, 'PatientID': patient_id, 'StudyDate': study_date,
C:\Users\esteb\AppData\Local\Temp\ipykernel_5656\3567807760.py:21: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append({'File': file_path, 'PatientID': patient_id, 'StudyDate': study_date,
C:\Users\esteb\AppData\Local\Temp\ipykernel_5656\3567807760.py:21: FutureWarning: The frame.append method is deprecated and will be removed

1-025.dcm
C:/Users/esteb/OneDrive - Universidad Politecnica Salesiana/Papers/Cancer cerebral/Dataset/manifest-1678464337678/Brain-TR-GammaKnife/GK_103/04-18-2014-NA-MR GAMMA KNIFE PLANNING BRAIN W IV CONTRAST-49648/4.000000-t1mprtraiso-40897/1-025.dcm
GK_103
20140418
No image data

1-026.dcm
C:/Users/esteb/OneDrive - Universidad Politecnica Salesiana/Papers/Cancer cerebral/Dataset/manifest-1678464337678/Brain-TR-GammaKnife/GK_103/04-18-2014-NA-MR GAMMA KNIFE PLANNING BRAIN W IV CONTRAST-49648/4.000000-t1mprtraiso-40897/1-026.dcm
GK_103
20140418
No image data

1-027.dcm
C:/Users/esteb/OneDrive - Universidad Politecnica Salesiana/Papers/Cancer cerebral/Dataset/manifest-1678464337678/Brain-TR-GammaKnife/GK_103/04-18-2014-NA-MR GAMMA KNIFE PLANNING BRAIN W IV CONTRAST-49648/4.000000-t1mprtraiso-40897/1-027.dcm
GK_103
20140418
No image data

1-028.dcm
C:/Users/esteb/OneDrive - Universidad Politecnica Salesiana/Papers/Cancer cerebral/Dataset/manifest-1678464337678/Brain-TR-GammaKnife/GK_103/

C:\Users\esteb\AppData\Local\Temp\ipykernel_5656\3567807760.py:21: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append({'File': file_path, 'PatientID': patient_id, 'StudyDate': study_date,
C:\Users\esteb\AppData\Local\Temp\ipykernel_5656\3567807760.py:21: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append({'File': file_path, 'PatientID': patient_id, 'StudyDate': study_date,
C:\Users\esteb\AppData\Local\Temp\ipykernel_5656\3567807760.py:21: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append({'File': file_path, 'PatientID': patient_id, 'StudyDate': study_date,
C:\Users\esteb\AppData\Local\Temp\ipykernel_5656\3567807760.py:21: FutureWarning: The frame.append method is deprecated and will be removed

1-044.dcm
C:/Users/esteb/OneDrive - Universidad Politecnica Salesiana/Papers/Cancer cerebral/Dataset/manifest-1678464337678/Brain-TR-GammaKnife/GK_103/04-18-2014-NA-MR GAMMA KNIFE PLANNING BRAIN W IV CONTRAST-49648/4.000000-t1mprtraiso-40897/1-044.dcm
GK_103
20140418
No image data

1-045.dcm
C:/Users/esteb/OneDrive - Universidad Politecnica Salesiana/Papers/Cancer cerebral/Dataset/manifest-1678464337678/Brain-TR-GammaKnife/GK_103/04-18-2014-NA-MR GAMMA KNIFE PLANNING BRAIN W IV CONTRAST-49648/4.000000-t1mprtraiso-40897/1-045.dcm
GK_103
20140418
No image data

1-046.dcm
C:/Users/esteb/OneDrive - Universidad Politecnica Salesiana/Papers/Cancer cerebral/Dataset/manifest-1678464337678/Brain-TR-GammaKnife/GK_103/04-18-2014-NA-MR GAMMA KNIFE PLANNING BRAIN W IV CONTRAST-49648/4.000000-t1mprtraiso-40897/1-046.dcm
GK_103
20140418
No image data

1-047.dcm
C:/Users/esteb/OneDrive - Universidad Politecnica Salesiana/Papers/Cancer cerebral/Dataset/manifest-1678464337678/Brain-TR-GammaKnife/GK_103/

C:\Users\esteb\AppData\Local\Temp\ipykernel_5656\3567807760.py:21: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append({'File': file_path, 'PatientID': patient_id, 'StudyDate': study_date,
C:\Users\esteb\AppData\Local\Temp\ipykernel_5656\3567807760.py:21: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append({'File': file_path, 'PatientID': patient_id, 'StudyDate': study_date,
C:\Users\esteb\AppData\Local\Temp\ipykernel_5656\3567807760.py:21: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append({'File': file_path, 'PatientID': patient_id, 'StudyDate': study_date,
C:\Users\esteb\AppData\Local\Temp\ipykernel_5656\3567807760.py:21: FutureWarning: The frame.append method is deprecated and will be removed

1-056.dcm
C:/Users/esteb/OneDrive - Universidad Politecnica Salesiana/Papers/Cancer cerebral/Dataset/manifest-1678464337678/Brain-TR-GammaKnife/GK_103/04-18-2014-NA-MR GAMMA KNIFE PLANNING BRAIN W IV CONTRAST-49648/4.000000-t1mprtraiso-40897/1-056.dcm
GK_103
20140418
No image data

1-057.dcm
C:/Users/esteb/OneDrive - Universidad Politecnica Salesiana/Papers/Cancer cerebral/Dataset/manifest-1678464337678/Brain-TR-GammaKnife/GK_103/04-18-2014-NA-MR GAMMA KNIFE PLANNING BRAIN W IV CONTRAST-49648/4.000000-t1mprtraiso-40897/1-057.dcm
GK_103
20140418
No image data

1-058.dcm
C:/Users/esteb/OneDrive - Universidad Politecnica Salesiana/Papers/Cancer cerebral/Dataset/manifest-1678464337678/Brain-TR-GammaKnife/GK_103/04-18-2014-NA-MR GAMMA KNIFE PLANNING BRAIN W IV CONTRAST-49648/4.000000-t1mprtraiso-40897/1-058.dcm
GK_103
20140418
No image data

1-059.dcm
C:/Users/esteb/OneDrive - Universidad Politecnica Salesiana/Papers/Cancer cerebral/Dataset/manifest-1678464337678/Brain-TR-GammaKnife/GK_103/

C:\Users\esteb\AppData\Local\Temp\ipykernel_5656\3567807760.py:21: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append({'File': file_path, 'PatientID': patient_id, 'StudyDate': study_date,
C:\Users\esteb\AppData\Local\Temp\ipykernel_5656\3567807760.py:21: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append({'File': file_path, 'PatientID': patient_id, 'StudyDate': study_date,
C:\Users\esteb\AppData\Local\Temp\ipykernel_5656\3567807760.py:21: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append({'File': file_path, 'PatientID': patient_id, 'StudyDate': study_date,
C:\Users\esteb\AppData\Local\Temp\ipykernel_5656\3567807760.py:21: FutureWarning: The frame.append method is deprecated and will be removed

1-068.dcm
C:/Users/esteb/OneDrive - Universidad Politecnica Salesiana/Papers/Cancer cerebral/Dataset/manifest-1678464337678/Brain-TR-GammaKnife/GK_103/04-18-2014-NA-MR GAMMA KNIFE PLANNING BRAIN W IV CONTRAST-49648/4.000000-t1mprtraiso-40897/1-068.dcm
GK_103
20140418
No image data

1-069.dcm
C:/Users/esteb/OneDrive - Universidad Politecnica Salesiana/Papers/Cancer cerebral/Dataset/manifest-1678464337678/Brain-TR-GammaKnife/GK_103/04-18-2014-NA-MR GAMMA KNIFE PLANNING BRAIN W IV CONTRAST-49648/4.000000-t1mprtraiso-40897/1-069.dcm
GK_103
20140418
No image data

1-070.dcm
C:/Users/esteb/OneDrive - Universidad Politecnica Salesiana/Papers/Cancer cerebral/Dataset/manifest-1678464337678/Brain-TR-GammaKnife/GK_103/04-18-2014-NA-MR GAMMA KNIFE PLANNING BRAIN W IV CONTRAST-49648/4.000000-t1mprtraiso-40897/1-070.dcm
GK_103
20140418
No image data

1-071.dcm
C:/Users/esteb/OneDrive - Universidad Politecnica Salesiana/Papers/Cancer cerebral/Dataset/manifest-1678464337678/Brain-TR-GammaKnife/GK_103/

C:\Users\esteb\AppData\Local\Temp\ipykernel_5656\3567807760.py:21: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append({'File': file_path, 'PatientID': patient_id, 'StudyDate': study_date,
C:\Users\esteb\AppData\Local\Temp\ipykernel_5656\3567807760.py:21: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append({'File': file_path, 'PatientID': patient_id, 'StudyDate': study_date,
C:\Users\esteb\AppData\Local\Temp\ipykernel_5656\3567807760.py:21: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append({'File': file_path, 'PatientID': patient_id, 'StudyDate': study_date,
C:\Users\esteb\AppData\Local\Temp\ipykernel_5656\3567807760.py:21: FutureWarning: The frame.append method is deprecated and will be removed

No image data

1-086.dcm
C:/Users/esteb/OneDrive - Universidad Politecnica Salesiana/Papers/Cancer cerebral/Dataset/manifest-1678464337678/Brain-TR-GammaKnife/GK_103/04-18-2014-NA-MR GAMMA KNIFE PLANNING BRAIN W IV CONTRAST-49648/4.000000-t1mprtraiso-40897/1-086.dcm
GK_103
20140418
No image data

1-087.dcm
C:/Users/esteb/OneDrive - Universidad Politecnica Salesiana/Papers/Cancer cerebral/Dataset/manifest-1678464337678/Brain-TR-GammaKnife/GK_103/04-18-2014-NA-MR GAMMA KNIFE PLANNING BRAIN W IV CONTRAST-49648/4.000000-t1mprtraiso-40897/1-087.dcm
GK_103
20140418
No image data

1-088.dcm
C:/Users/esteb/OneDrive - Universidad Politecnica Salesiana/Papers/Cancer cerebral/Dataset/manifest-1678464337678/Brain-TR-GammaKnife/GK_103/04-18-2014-NA-MR GAMMA KNIFE PLANNING BRAIN W IV CONTRAST-49648/4.000000-t1mprtraiso-40897/1-088.dcm
GK_103
20140418
No image data

1-089.dcm
C:/Users/esteb/OneDrive - Universidad Politecnica Salesiana/Papers/Cancer cerebral/Dataset/manifest-1678464337678/Brain-TR-Gam

C:\Users\esteb\AppData\Local\Temp\ipykernel_5656\3567807760.py:21: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append({'File': file_path, 'PatientID': patient_id, 'StudyDate': study_date,
C:\Users\esteb\AppData\Local\Temp\ipykernel_5656\3567807760.py:21: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append({'File': file_path, 'PatientID': patient_id, 'StudyDate': study_date,
C:\Users\esteb\AppData\Local\Temp\ipykernel_5656\3567807760.py:21: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append({'File': file_path, 'PatientID': patient_id, 'StudyDate': study_date,
C:\Users\esteb\AppData\Local\Temp\ipykernel_5656\3567807760.py:21: FutureWarning: The frame.append method is deprecated and will be removed

1-108.dcm
C:/Users/esteb/OneDrive - Universidad Politecnica Salesiana/Papers/Cancer cerebral/Dataset/manifest-1678464337678/Brain-TR-GammaKnife/GK_103/04-18-2014-NA-MR GAMMA KNIFE PLANNING BRAIN W IV CONTRAST-49648/4.000000-t1mprtraiso-40897/1-108.dcm
GK_103
20140418
No image data

1-109.dcm
C:/Users/esteb/OneDrive - Universidad Politecnica Salesiana/Papers/Cancer cerebral/Dataset/manifest-1678464337678/Brain-TR-GammaKnife/GK_103/04-18-2014-NA-MR GAMMA KNIFE PLANNING BRAIN W IV CONTRAST-49648/4.000000-t1mprtraiso-40897/1-109.dcm
GK_103
20140418
No image data

1-110.dcm
C:/Users/esteb/OneDrive - Universidad Politecnica Salesiana/Papers/Cancer cerebral/Dataset/manifest-1678464337678/Brain-TR-GammaKnife/GK_103/04-18-2014-NA-MR GAMMA KNIFE PLANNING BRAIN W IV CONTRAST-49648/4.000000-t1mprtraiso-40897/1-110.dcm
GK_103
20140418
No image data

1-111.dcm
C:/Users/esteb/OneDrive - Universidad Politecnica Salesiana/Papers/Cancer cerebral/Dataset/manifest-1678464337678/Brain-TR-GammaKnife/GK_103/

C:\Users\esteb\AppData\Local\Temp\ipykernel_5656\3567807760.py:21: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append({'File': file_path, 'PatientID': patient_id, 'StudyDate': study_date,
C:\Users\esteb\AppData\Local\Temp\ipykernel_5656\3567807760.py:21: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append({'File': file_path, 'PatientID': patient_id, 'StudyDate': study_date,
C:\Users\esteb\AppData\Local\Temp\ipykernel_5656\3567807760.py:21: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append({'File': file_path, 'PatientID': patient_id, 'StudyDate': study_date,
C:\Users\esteb\AppData\Local\Temp\ipykernel_5656\3567807760.py:21: FutureWarning: The frame.append method is deprecated and will be removed

1-120.dcm
C:/Users/esteb/OneDrive - Universidad Politecnica Salesiana/Papers/Cancer cerebral/Dataset/manifest-1678464337678/Brain-TR-GammaKnife/GK_103/04-18-2014-NA-MR GAMMA KNIFE PLANNING BRAIN W IV CONTRAST-49648/4.000000-t1mprtraiso-40897/1-120.dcm
GK_103
20140418
No image data

1-121.dcm
C:/Users/esteb/OneDrive - Universidad Politecnica Salesiana/Papers/Cancer cerebral/Dataset/manifest-1678464337678/Brain-TR-GammaKnife/GK_103/04-18-2014-NA-MR GAMMA KNIFE PLANNING BRAIN W IV CONTRAST-49648/4.000000-t1mprtraiso-40897/1-121.dcm
GK_103
20140418
No image data

1-122.dcm
C:/Users/esteb/OneDrive - Universidad Politecnica Salesiana/Papers/Cancer cerebral/Dataset/manifest-1678464337678/Brain-TR-GammaKnife/GK_103/04-18-2014-NA-MR GAMMA KNIFE PLANNING BRAIN W IV CONTRAST-49648/4.000000-t1mprtraiso-40897/1-122.dcm
GK_103
20140418
No image data

1-123.dcm
C:/Users/esteb/OneDrive - Universidad Politecnica Salesiana/Papers/Cancer cerebral/Dataset/manifest-1678464337678/Brain-TR-GammaKnife/GK_103/

C:\Users\esteb\AppData\Local\Temp\ipykernel_5656\3567807760.py:21: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append({'File': file_path, 'PatientID': patient_id, 'StudyDate': study_date,
C:\Users\esteb\AppData\Local\Temp\ipykernel_5656\3567807760.py:21: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append({'File': file_path, 'PatientID': patient_id, 'StudyDate': study_date,
C:\Users\esteb\AppData\Local\Temp\ipykernel_5656\3567807760.py:21: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append({'File': file_path, 'PatientID': patient_id, 'StudyDate': study_date,
C:\Users\esteb\AppData\Local\Temp\ipykernel_5656\3567807760.py:21: FutureWarning: The frame.append method is deprecated and will be removed

1-133.dcm
C:/Users/esteb/OneDrive - Universidad Politecnica Salesiana/Papers/Cancer cerebral/Dataset/manifest-1678464337678/Brain-TR-GammaKnife/GK_103/04-18-2014-NA-MR GAMMA KNIFE PLANNING BRAIN W IV CONTRAST-49648/4.000000-t1mprtraiso-40897/1-133.dcm
GK_103
20140418
No image data

1-134.dcm
C:/Users/esteb/OneDrive - Universidad Politecnica Salesiana/Papers/Cancer cerebral/Dataset/manifest-1678464337678/Brain-TR-GammaKnife/GK_103/04-18-2014-NA-MR GAMMA KNIFE PLANNING BRAIN W IV CONTRAST-49648/4.000000-t1mprtraiso-40897/1-134.dcm
GK_103
20140418
No image data

1-135.dcm
C:/Users/esteb/OneDrive - Universidad Politecnica Salesiana/Papers/Cancer cerebral/Dataset/manifest-1678464337678/Brain-TR-GammaKnife/GK_103/04-18-2014-NA-MR GAMMA KNIFE PLANNING BRAIN W IV CONTRAST-49648/4.000000-t1mprtraiso-40897/1-135.dcm
GK_103
20140418
No image data

1-136.dcm
C:/Users/esteb/OneDrive - Universidad Politecnica Salesiana/Papers/Cancer cerebral/Dataset/manifest-1678464337678/Brain-TR-GammaKnife/GK_103/

C:\Users\esteb\AppData\Local\Temp\ipykernel_5656\3567807760.py:21: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append({'File': file_path, 'PatientID': patient_id, 'StudyDate': study_date,
C:\Users\esteb\AppData\Local\Temp\ipykernel_5656\3567807760.py:21: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append({'File': file_path, 'PatientID': patient_id, 'StudyDate': study_date,
C:\Users\esteb\AppData\Local\Temp\ipykernel_5656\3567807760.py:21: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append({'File': file_path, 'PatientID': patient_id, 'StudyDate': study_date,
C:\Users\esteb\AppData\Local\Temp\ipykernel_5656\3567807760.py:21: FutureWarning: The frame.append method is deprecated and will be removed

No image data

1-150.dcm
C:/Users/esteb/OneDrive - Universidad Politecnica Salesiana/Papers/Cancer cerebral/Dataset/manifest-1678464337678/Brain-TR-GammaKnife/GK_103/04-18-2014-NA-MR GAMMA KNIFE PLANNING BRAIN W IV CONTRAST-49648/4.000000-t1mprtraiso-40897/1-150.dcm
GK_103
20140418
No image data

1-151.dcm
C:/Users/esteb/OneDrive - Universidad Politecnica Salesiana/Papers/Cancer cerebral/Dataset/manifest-1678464337678/Brain-TR-GammaKnife/GK_103/04-18-2014-NA-MR GAMMA KNIFE PLANNING BRAIN W IV CONTRAST-49648/4.000000-t1mprtraiso-40897/1-151.dcm
GK_103
20140418
No image data

1-152.dcm
C:/Users/esteb/OneDrive - Universidad Politecnica Salesiana/Papers/Cancer cerebral/Dataset/manifest-1678464337678/Brain-TR-GammaKnife/GK_103/04-18-2014-NA-MR GAMMA KNIFE PLANNING BRAIN W IV CONTRAST-49648/4.000000-t1mprtraiso-40897/1-152.dcm
GK_103
20140418
No image data

1-153.dcm
C:/Users/esteb/OneDrive - Universidad Politecnica Salesiana/Papers/Cancer cerebral/Dataset/manifest-1678464337678/Brain-TR-Gam

C:\Users\esteb\AppData\Local\Temp\ipykernel_5656\3567807760.py:21: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append({'File': file_path, 'PatientID': patient_id, 'StudyDate': study_date,
C:\Users\esteb\AppData\Local\Temp\ipykernel_5656\3567807760.py:21: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append({'File': file_path, 'PatientID': patient_id, 'StudyDate': study_date,
C:\Users\esteb\AppData\Local\Temp\ipykernel_5656\3567807760.py:21: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append({'File': file_path, 'PatientID': patient_id, 'StudyDate': study_date,
C:\Users\esteb\AppData\Local\Temp\ipykernel_5656\3567807760.py:21: FutureWarning: The frame.append method is deprecated and will be removed

1-167.dcm
C:/Users/esteb/OneDrive - Universidad Politecnica Salesiana/Papers/Cancer cerebral/Dataset/manifest-1678464337678/Brain-TR-GammaKnife/GK_103/04-18-2014-NA-MR GAMMA KNIFE PLANNING BRAIN W IV CONTRAST-49648/4.000000-t1mprtraiso-40897/1-167.dcm
GK_103
20140418
No image data

1-168.dcm
C:/Users/esteb/OneDrive - Universidad Politecnica Salesiana/Papers/Cancer cerebral/Dataset/manifest-1678464337678/Brain-TR-GammaKnife/GK_103/04-18-2014-NA-MR GAMMA KNIFE PLANNING BRAIN W IV CONTRAST-49648/4.000000-t1mprtraiso-40897/1-168.dcm
GK_103
20140418
No image data

1-169.dcm
C:/Users/esteb/OneDrive - Universidad Politecnica Salesiana/Papers/Cancer cerebral/Dataset/manifest-1678464337678/Brain-TR-GammaKnife/GK_103/04-18-2014-NA-MR GAMMA KNIFE PLANNING BRAIN W IV CONTRAST-49648/4.000000-t1mprtraiso-40897/1-169.dcm
GK_103
20140418
No image data

1-170.dcm
C:/Users/esteb/OneDrive - Universidad Politecnica Salesiana/Papers/Cancer cerebral/Dataset/manifest-1678464337678/Brain-TR-GammaKnife/GK_103/

C:\Users\esteb\AppData\Local\Temp\ipykernel_5656\3567807760.py:21: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append({'File': file_path, 'PatientID': patient_id, 'StudyDate': study_date,
C:\Users\esteb\AppData\Local\Temp\ipykernel_5656\3567807760.py:21: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append({'File': file_path, 'PatientID': patient_id, 'StudyDate': study_date,
C:\Users\esteb\AppData\Local\Temp\ipykernel_5656\3567807760.py:21: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append({'File': file_path, 'PatientID': patient_id, 'StudyDate': study_date,
C:\Users\esteb\AppData\Local\Temp\ipykernel_5656\3567807760.py:21: FutureWarning: The frame.append method is deprecated and will be removed

1-182.dcm
C:/Users/esteb/OneDrive - Universidad Politecnica Salesiana/Papers/Cancer cerebral/Dataset/manifest-1678464337678/Brain-TR-GammaKnife/GK_103/04-18-2014-NA-MR GAMMA KNIFE PLANNING BRAIN W IV CONTRAST-49648/4.000000-t1mprtraiso-40897/1-182.dcm
GK_103
20140418
No image data

1-183.dcm
C:/Users/esteb/OneDrive - Universidad Politecnica Salesiana/Papers/Cancer cerebral/Dataset/manifest-1678464337678/Brain-TR-GammaKnife/GK_103/04-18-2014-NA-MR GAMMA KNIFE PLANNING BRAIN W IV CONTRAST-49648/4.000000-t1mprtraiso-40897/1-183.dcm
GK_103
20140418
No image data

1-184.dcm
C:/Users/esteb/OneDrive - Universidad Politecnica Salesiana/Papers/Cancer cerebral/Dataset/manifest-1678464337678/Brain-TR-GammaKnife/GK_103/04-18-2014-NA-MR GAMMA KNIFE PLANNING BRAIN W IV CONTRAST-49648/4.000000-t1mprtraiso-40897/1-184.dcm
GK_103
20140418
No image data

1-185.dcm
C:/Users/esteb/OneDrive - Universidad Politecnica Salesiana/Papers/Cancer cerebral/Dataset/manifest-1678464337678/Brain-TR-GammaKnife/GK_103/

C:\Users\esteb\AppData\Local\Temp\ipykernel_5656\3567807760.py:21: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append({'File': file_path, 'PatientID': patient_id, 'StudyDate': study_date,
C:\Users\esteb\AppData\Local\Temp\ipykernel_5656\3567807760.py:21: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append({'File': file_path, 'PatientID': patient_id, 'StudyDate': study_date,
C:\Users\esteb\AppData\Local\Temp\ipykernel_5656\3567807760.py:21: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append({'File': file_path, 'PatientID': patient_id, 'StudyDate': study_date,
C:\Users\esteb\AppData\Local\Temp\ipykernel_5656\3567807760.py:21: FutureWarning: The frame.append method is deprecated and will be removed

1-199.dcm
C:/Users/esteb/OneDrive - Universidad Politecnica Salesiana/Papers/Cancer cerebral/Dataset/manifest-1678464337678/Brain-TR-GammaKnife/GK_103/04-18-2014-NA-MR GAMMA KNIFE PLANNING BRAIN W IV CONTRAST-49648/4.000000-t1mprtraiso-40897/1-199.dcm
GK_103
20140418
No image data

1-200.dcm
C:/Users/esteb/OneDrive - Universidad Politecnica Salesiana/Papers/Cancer cerebral/Dataset/manifest-1678464337678/Brain-TR-GammaKnife/GK_103/04-18-2014-NA-MR GAMMA KNIFE PLANNING BRAIN W IV CONTRAST-49648/4.000000-t1mprtraiso-40897/1-200.dcm
GK_103
20140418
No image data

1-201.dcm
C:/Users/esteb/OneDrive - Universidad Politecnica Salesiana/Papers/Cancer cerebral/Dataset/manifest-1678464337678/Brain-TR-GammaKnife/GK_103/04-18-2014-NA-MR GAMMA KNIFE PLANNING BRAIN W IV CONTRAST-49648/4.000000-t1mprtraiso-40897/1-201.dcm
GK_103
20140418
No image data

1-202.dcm
C:/Users/esteb/OneDrive - Universidad Politecnica Salesiana/Papers/Cancer cerebral/Dataset/manifest-1678464337678/Brain-TR-GammaKnife/GK_103/

C:\Users\esteb\AppData\Local\Temp\ipykernel_5656\3567807760.py:21: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append({'File': file_path, 'PatientID': patient_id, 'StudyDate': study_date,
C:\Users\esteb\AppData\Local\Temp\ipykernel_5656\3567807760.py:21: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append({'File': file_path, 'PatientID': patient_id, 'StudyDate': study_date,
C:\Users\esteb\AppData\Local\Temp\ipykernel_5656\3567807760.py:21: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append({'File': file_path, 'PatientID': patient_id, 'StudyDate': study_date,
C:\Users\esteb\AppData\Local\Temp\ipykernel_5656\3567807760.py:21: FutureWarning: The frame.append method is deprecated and will be removed

No image data

1-006.dcm
C:/Users/esteb/OneDrive - Universidad Politecnica Salesiana/Papers/Cancer cerebral/Dataset/manifest-1678464337678/Brain-TR-GammaKnife/GK_103/12-18-2014-NA-MR BRAIN W WO IV CONTRAST-94259/13.000000-t1mprtraiso-42794/1-006.dcm
GK_103
20141218
No image data

1-007.dcm
C:/Users/esteb/OneDrive - Universidad Politecnica Salesiana/Papers/Cancer cerebral/Dataset/manifest-1678464337678/Brain-TR-GammaKnife/GK_103/12-18-2014-NA-MR BRAIN W WO IV CONTRAST-94259/13.000000-t1mprtraiso-42794/1-007.dcm
GK_103
20141218
No image data

1-008.dcm
C:/Users/esteb/OneDrive - Universidad Politecnica Salesiana/Papers/Cancer cerebral/Dataset/manifest-1678464337678/Brain-TR-GammaKnife/GK_103/12-18-2014-NA-MR BRAIN W WO IV CONTRAST-94259/13.000000-t1mprtraiso-42794/1-008.dcm
GK_103
20141218
No image data

1-009.dcm
C:/Users/esteb/OneDrive - Universidad Politecnica Salesiana/Papers/Cancer cerebral/Dataset/manifest-1678464337678/Brain-TR-GammaKnife/GK_103/12-18-2014-NA-MR BRAIN W WO IV CONTR

C:\Users\esteb\AppData\Local\Temp\ipykernel_5656\3567807760.py:21: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append({'File': file_path, 'PatientID': patient_id, 'StudyDate': study_date,
C:\Users\esteb\AppData\Local\Temp\ipykernel_5656\3567807760.py:21: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append({'File': file_path, 'PatientID': patient_id, 'StudyDate': study_date,
C:\Users\esteb\AppData\Local\Temp\ipykernel_5656\3567807760.py:21: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append({'File': file_path, 'PatientID': patient_id, 'StudyDate': study_date,
C:\Users\esteb\AppData\Local\Temp\ipykernel_5656\3567807760.py:21: FutureWarning: The frame.append method is deprecated and will be removed

1-022.dcm
C:/Users/esteb/OneDrive - Universidad Politecnica Salesiana/Papers/Cancer cerebral/Dataset/manifest-1678464337678/Brain-TR-GammaKnife/GK_103/12-18-2014-NA-MR BRAIN W WO IV CONTRAST-94259/13.000000-t1mprtraiso-42794/1-022.dcm
GK_103
20141218
No image data

1-023.dcm
C:/Users/esteb/OneDrive - Universidad Politecnica Salesiana/Papers/Cancer cerebral/Dataset/manifest-1678464337678/Brain-TR-GammaKnife/GK_103/12-18-2014-NA-MR BRAIN W WO IV CONTRAST-94259/13.000000-t1mprtraiso-42794/1-023.dcm
GK_103
20141218
No image data

1-024.dcm
C:/Users/esteb/OneDrive - Universidad Politecnica Salesiana/Papers/Cancer cerebral/Dataset/manifest-1678464337678/Brain-TR-GammaKnife/GK_103/12-18-2014-NA-MR BRAIN W WO IV CONTRAST-94259/13.000000-t1mprtraiso-42794/1-024.dcm
GK_103
20141218
No image data

1-025.dcm
C:/Users/esteb/OneDrive - Universidad Politecnica Salesiana/Papers/Cancer cerebral/Dataset/manifest-1678464337678/Brain-TR-GammaKnife/GK_103/12-18-2014-NA-MR BRAIN W WO IV CONTRAST-94259/13.00

C:\Users\esteb\AppData\Local\Temp\ipykernel_5656\3567807760.py:21: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append({'File': file_path, 'PatientID': patient_id, 'StudyDate': study_date,
C:\Users\esteb\AppData\Local\Temp\ipykernel_5656\3567807760.py:21: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append({'File': file_path, 'PatientID': patient_id, 'StudyDate': study_date,
C:\Users\esteb\AppData\Local\Temp\ipykernel_5656\3567807760.py:21: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append({'File': file_path, 'PatientID': patient_id, 'StudyDate': study_date,
C:\Users\esteb\AppData\Local\Temp\ipykernel_5656\3567807760.py:21: FutureWarning: The frame.append method is deprecated and will be removed

1-042.dcm
C:/Users/esteb/OneDrive - Universidad Politecnica Salesiana/Papers/Cancer cerebral/Dataset/manifest-1678464337678/Brain-TR-GammaKnife/GK_103/12-18-2014-NA-MR BRAIN W WO IV CONTRAST-94259/13.000000-t1mprtraiso-42794/1-042.dcm
GK_103
20141218
No image data

1-043.dcm
C:/Users/esteb/OneDrive - Universidad Politecnica Salesiana/Papers/Cancer cerebral/Dataset/manifest-1678464337678/Brain-TR-GammaKnife/GK_103/12-18-2014-NA-MR BRAIN W WO IV CONTRAST-94259/13.000000-t1mprtraiso-42794/1-043.dcm
GK_103
20141218
No image data

1-044.dcm
C:/Users/esteb/OneDrive - Universidad Politecnica Salesiana/Papers/Cancer cerebral/Dataset/manifest-1678464337678/Brain-TR-GammaKnife/GK_103/12-18-2014-NA-MR BRAIN W WO IV CONTRAST-94259/13.000000-t1mprtraiso-42794/1-044.dcm
GK_103
20141218
No image data

1-045.dcm
C:/Users/esteb/OneDrive - Universidad Politecnica Salesiana/Papers/Cancer cerebral/Dataset/manifest-1678464337678/Brain-TR-GammaKnife/GK_103/12-18-2014-NA-MR BRAIN W WO IV CONTRAST-94259/13.00

C:\Users\esteb\AppData\Local\Temp\ipykernel_5656\3567807760.py:21: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append({'File': file_path, 'PatientID': patient_id, 'StudyDate': study_date,
C:\Users\esteb\AppData\Local\Temp\ipykernel_5656\3567807760.py:21: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append({'File': file_path, 'PatientID': patient_id, 'StudyDate': study_date,
C:\Users\esteb\AppData\Local\Temp\ipykernel_5656\3567807760.py:21: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append({'File': file_path, 'PatientID': patient_id, 'StudyDate': study_date,
C:\Users\esteb\AppData\Local\Temp\ipykernel_5656\3567807760.py:21: FutureWarning: The frame.append method is deprecated and will be removed

1-065.dcm
C:/Users/esteb/OneDrive - Universidad Politecnica Salesiana/Papers/Cancer cerebral/Dataset/manifest-1678464337678/Brain-TR-GammaKnife/GK_103/12-18-2014-NA-MR BRAIN W WO IV CONTRAST-94259/13.000000-t1mprtraiso-42794/1-065.dcm
GK_103
20141218
No image data

1-066.dcm
C:/Users/esteb/OneDrive - Universidad Politecnica Salesiana/Papers/Cancer cerebral/Dataset/manifest-1678464337678/Brain-TR-GammaKnife/GK_103/12-18-2014-NA-MR BRAIN W WO IV CONTRAST-94259/13.000000-t1mprtraiso-42794/1-066.dcm
GK_103
20141218
No image data

1-067.dcm
C:/Users/esteb/OneDrive - Universidad Politecnica Salesiana/Papers/Cancer cerebral/Dataset/manifest-1678464337678/Brain-TR-GammaKnife/GK_103/12-18-2014-NA-MR BRAIN W WO IV CONTRAST-94259/13.000000-t1mprtraiso-42794/1-067.dcm
GK_103
20141218
No image data

1-068.dcm
C:/Users/esteb/OneDrive - Universidad Politecnica Salesiana/Papers/Cancer cerebral/Dataset/manifest-1678464337678/Brain-TR-GammaKnife/GK_103/12-18-2014-NA-MR BRAIN W WO IV CONTRAST-94259/13.00

C:\Users\esteb\AppData\Local\Temp\ipykernel_5656\3567807760.py:21: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append({'File': file_path, 'PatientID': patient_id, 'StudyDate': study_date,
C:\Users\esteb\AppData\Local\Temp\ipykernel_5656\3567807760.py:21: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append({'File': file_path, 'PatientID': patient_id, 'StudyDate': study_date,
C:\Users\esteb\AppData\Local\Temp\ipykernel_5656\3567807760.py:21: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append({'File': file_path, 'PatientID': patient_id, 'StudyDate': study_date,
C:\Users\esteb\AppData\Local\Temp\ipykernel_5656\3567807760.py:21: FutureWarning: The frame.append method is deprecated and will be removed

1-089.dcm
C:/Users/esteb/OneDrive - Universidad Politecnica Salesiana/Papers/Cancer cerebral/Dataset/manifest-1678464337678/Brain-TR-GammaKnife/GK_103/12-18-2014-NA-MR BRAIN W WO IV CONTRAST-94259/13.000000-t1mprtraiso-42794/1-089.dcm
GK_103
20141218
No image data

1-090.dcm
C:/Users/esteb/OneDrive - Universidad Politecnica Salesiana/Papers/Cancer cerebral/Dataset/manifest-1678464337678/Brain-TR-GammaKnife/GK_103/12-18-2014-NA-MR BRAIN W WO IV CONTRAST-94259/13.000000-t1mprtraiso-42794/1-090.dcm
GK_103
20141218
No image data

1-091.dcm
C:/Users/esteb/OneDrive - Universidad Politecnica Salesiana/Papers/Cancer cerebral/Dataset/manifest-1678464337678/Brain-TR-GammaKnife/GK_103/12-18-2014-NA-MR BRAIN W WO IV CONTRAST-94259/13.000000-t1mprtraiso-42794/1-091.dcm
GK_103
20141218
No image data

1-092.dcm
C:/Users/esteb/OneDrive - Universidad Politecnica Salesiana/Papers/Cancer cerebral/Dataset/manifest-1678464337678/Brain-TR-GammaKnife/GK_103/12-18-2014-NA-MR BRAIN W WO IV CONTRAST-94259/13.00

C:\Users\esteb\AppData\Local\Temp\ipykernel_5656\3567807760.py:21: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append({'File': file_path, 'PatientID': patient_id, 'StudyDate': study_date,


KeyboardInterrupt: 

In [78]:
count = 0
for subdir, dirs, files in os.walk(root_dir):
    for file in files:
         # Check if the file is a DICOM image
        if file.endswith('.dcm'):
            # Create the full file path
            if(count<20):
                file_path = os.path.join(subdir, file)
                dcm = pydicom.dcmread(file_path)
                
                try:
                    type = dcm.SOPClassUID
                    print(type)
                    print(dcm.data_element('SOPClassUID'))
                except:
                    print("no data")
                count += 1
                

1.2.840.10008.5.1.4.1.1.481.3
(0008, 0016) SOP Class UID                       UI: RT Structure Set Storage
1.2.840.10008.5.1.4.1.1.481.2
(0008, 0016) SOP Class UID                       UI: RT Dose Storage
1.2.840.10008.5.1.4.1.1.4
(0008, 0016) SOP Class UID                       UI: MR Image Storage
1.2.840.10008.5.1.4.1.1.4
(0008, 0016) SOP Class UID                       UI: MR Image Storage
1.2.840.10008.5.1.4.1.1.4
(0008, 0016) SOP Class UID                       UI: MR Image Storage
1.2.840.10008.5.1.4.1.1.4
(0008, 0016) SOP Class UID                       UI: MR Image Storage
1.2.840.10008.5.1.4.1.1.4
(0008, 0016) SOP Class UID                       UI: MR Image Storage
1.2.840.10008.5.1.4.1.1.4
(0008, 0016) SOP Class UID                       UI: MR Image Storage
1.2.840.10008.5.1.4.1.1.4
(0008, 0016) SOP Class UID                       UI: MR Image Storage
1.2.840.10008.5.1.4.1.1.4
(0008, 0016) SOP Class UID                       UI: MR Image Storage
1.2.840.10008.5.1.4.1.1.4